from abc import abstractmethod
from collections import deque

from pandas import DataFrame
from mesa import Agent


class BaseUE(Agent):
    def __init__(self, ue_id: int, sim_model=None):
        """
        Initialize the ue.
        """
        super().__init__(ue_id, sim_model)

        self.sim_model = sim_model
        self.active = False

        self.positions: DataFrame | None = None
        self.current_position = None
        self.start_time: int = 0
        self.end_time: int = 0

        self.ue_data = 0
        self.data_sent: bool = False
        self.ue_data_cache = deque(maxlen=2)

    @abstractmethod
    def step(self, *args, **kwargs):
        """
        Step function for the ue.
        """
        pass

    @abstractmethod
    def _generate_data(self) -> None:
        """
        Generate data for the ue.
        """
        pass

    def get_neighbour_data(self) -> dict[int, float]:
        """
        Get the data from the neighbours.
        """
        return {}

    @abstractmethod
    def _initiate_models(self) -> None:
        """
        Initiate the models related to this ue.
        """
        pass

    @abstractmethod
    def _deactivate_models(self) -> None:
        """
        Deactivate the models related to this ue.
        """
        pass

    @abstractmethod
    def set_mobility_data(self, positions: DataFrame) -> None:
        """
        Set the mobility data for the ue.
        """
        pass

    @abstractmethod
    def set_coverage_data(self, coverage: DataFrame) -> None:
        """
        Set the coverage data for the ue.
        """
        pass

    def set_data_transmit_status(self, flag: bool) -> None:
        """
        Set the data sent flag.
        """
        self.data_sent = flag

    def get_data_transmit_status(self) -> bool:
        """
        Get the data sent flag.
        """
        return self.data_sent

    def get_id(self) -> int:
        """
        Get the ue id.
        """
        return self.unique_id

    def get_position(self) -> list[float]:
        """
        Get the current position of the ue.
        """
        return self.current_position

    def is_active(self) -> bool:
        """
        Check if the ue is active.
        """
        return self.active

    def toggle_status(self):
        """
        Toggle the active status of the ue.
        """
        # Toggle the status
        self.active = not self.active

        if self.active:
            # Initiate the models
            self._initiate_models()
        else:
            # Deactivate the models
            self._deactivate_models()

    def get_data(self) -> float:
        """
        Get the data generated by the ue.
        """
        return self.ue_data

    def get_start_and_end_time(self) -> tuple[int, int]:
        """
        Get the start and end time of the ue.
        """
        return self.start_time, self.end_time

    def get_cached_data(self):
        """
        Get the data cached by the ue.
        """
        return self.ue_data_cache[-1]
