# Input file names
CC_VEHICLE_TRACE_FILE = "vehicle_traces"
CC_VEHICLE_ACTIVATIONS_FILE = "vehicle_activations"
CC_V2V_LINKS_FILE = "v2v_links"
CC_BASE_STATIONS_FILE = "base_stations"
CC_BASE_STATION_ACTIVATIONS_FILE = "base_station_activations"
CC_V2B_LINKS_FILE = "v2b_links"
CC_CONTROLLERS_FILE = "controllers"
CC_CONTROLLER_ACTIVATIONS_FILE = "controller_activations"
CC_B2C_LINKS_FILE = "b2c_links"

# Main columns in the input files
CC_VEHICLE_ID = "vehicle_id"
CC_TIME_STEP = "time_step"
CC_X = "x"
CC_Y = "y"
CC_NEIGHBOURS = "neighbours"
CC_DISTANCES = "distances"
CC_BASE_STATIONS = "base_stations"
CC_BASE_STATION_ID = "base_station_id"
CC_CONTROLLER_ID = "controller_id"
CC_START_TIME = "start_time"
CC_END_TIME = "end_time"
CC_LINK_ID = "link_id"

# Column names and data types for the input files
CC_VEHICLE_TRACE_COLUMN_NAMES = [CC_VEHICLE_ID, CC_TIME_STEP, CC_X, CC_Y]
CC_VEHICLE_TRACE_COLUMN_DTYPES = {CC_VEHICLE_ID: int, CC_TIME_STEP: float, CC_X: float, CC_Y: float}

CC_V2V_LINKS_COLUMN_NAMES = [CC_VEHICLE_ID, CC_TIME_STEP, CC_NEIGHBOURS, CC_DISTANCES]
CC_V2V_LINKS_COLUMN_DTYPES = {CC_VEHICLE_ID: int, CC_TIME_STEP: int, CC_NEIGHBOURS: str, CC_DISTANCES: str}

CC_BASE_STATION_COLUMN_NAMES = [CC_BASE_STATION_ID, CC_X, CC_Y]
CC_BASE_STATION_COLUMN_DTYPES = {CC_BASE_STATION_ID: int, CC_X: float, CC_Y: float}

CC_CONTROLLERS_COLUMN_NAMES = [CC_CONTROLLER_ID, CC_X, CC_Y]
CC_CONTROLLERS_COLUMN_DTYPES = {CC_CONTROLLER_ID: int, CC_X: float, CC_Y: float}

CC_V2B_LINKS_COLUMN_NAMES = [CC_VEHICLE_ID, CC_TIME_STEP, CC_BASE_STATIONS, CC_DISTANCES]
CC_V2B_LINKS_COLUMN_DTYPES = {CC_VEHICLE_ID: int, CC_TIME_STEP: int, CC_BASE_STATIONS: str, CC_DISTANCES: str}

CC_B2C_LINKS_COLUMN_NAMES = [CC_LINK_ID, CC_BASE_STATION_ID, CC_CONTROLLER_ID]
CC_B2C_LINKS_COLUMN_DTYPES = {CC_LINK_ID: int, CC_BASE_STATION_ID: int, CC_CONTROLLER_ID: int}

CC_ACTIVATION_TIMES_COLUMN_NAMES = [CC_VEHICLE_ID, CC_START_TIME, CC_END_TIME]
CC_ACTIVATION_TIMES_COLUMN_DTYPES = {CC_VEHICLE_ID: int, CC_START_TIME: str, CC_END_TIME: str}

# File extensions
CC_PARQUET: str = "parquet"
CC_CSV: str = "csv"
